# Generated by Django 4.0.1 on 2022-09-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('game_key', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('white_player', models.CharField(max_length=36)),
                ('black_player', models.CharField(max_length=36)),
                ('fen', models.CharField(max_length=87)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('move_number', models.IntegerField(default=0)),
                ('game_status', models.CharField(choices=[('O', 'Over'), ('A', 'Active')], max_length=1)),
            ],
        ),
    ]
