# Generated by Django 4.0.1 on 2022-09-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='black_player',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white_player',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
