# Generated by Django 4.0.1 on 2022-09-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chessgame_black_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='game_status',
            field=models.CharField(choices=[('O', 'Open'), ('A', 'Active'), ('D', 'Draw'), ('W', 'White Won'), ('B', 'Black Won')], max_length=1),
        ),
    ]
