# Generated by Django 4.0.1 on 2022-09-14 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_chessgame_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='black_rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='black_time_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white_rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white_time_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='black_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='black_player_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='white_player_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
