# Generated by Django 4.0.1 on 2022-09-14 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_chessgame_black_rating_chessgame_black_time_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='black_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black_player_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_player_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
